### PR TITLE
I've added option for Yes Button. 

### PR DESCRIPTION
**Pull request by madmaker**
Now it can be configured to be in different bootstrap-class: danger, primary, success etc.

### CODE REVIEW

**Comment by Ifnot** [comment]
Why changing the indentation ?

Nice idea by the way, but cannot identify the diff with the complete indentation change.

Could you look at it ?

**Comment by madmaker** [comment]
I don't know why my IDE has done it...

I've just changed 2 lines.

I've added:
, yesBtnClass: 'danger'

on line 30 in var defaults = { 
after 
noBtn: 'No' 

and changed 1 string on line 115
from 
content: options.content + '<p class="button-group" style="margin-top: 10px; text-align: center;"><button type="button" class="btn btn-small confirm-dialog-btn-abord">' + options.noBtn + '</button> <button type="button" class="btn btn-small btn-danger confirm-dialog-btn-confirm">' + options.yesBtn + '</button></p>'
to
content: options.content + '<p class="button-group" style="margin-top: 10px; text-align: center;"><button type="button" class="btn btn-small confirm-dialog-btn-abord">' + options.noBtn + '</button> <button type="button" class="btn btn-small btn-' +options.yesBtnClass+ ' confirm-dialog-btn-confirm">' + options.yesBtn + '</button></p>'

I've replaced btn-danger to btn-' +options.yesBtnClass+ '

Tat's really good thing if you want to confirm sumething not with danger button. For example if you confirm something to accept.

I can try to make another pull-request for it or just add theese changes yourself if you like it.

**Comment by Ifnot** [comment]
Okay i will take a look for doing manual editing :)

If you want to be in credits you can make another PR with good indentation ;)

**Comment by madmaker** [comment]
Thank you.

**Pull request closed without merging**
