### PR TITLE
Update jquery.popconfirm.js

### PR DESCRIPTION
**Pull request by markwylde**
Added onYes and onNo options to run a specific callback when buttons are clicked.

### CODE REVIEW

**Comment by Ifnot** [comment]
Ok for the merge :)

But what do you think about putting contributors on the package.json ?

I you're on it, i think all contribs should be here to. Maybe it will be a hudge work as we have to do the same thing on `bower.json`

**Comment by mrdnote** [comment]
I think this is a very useful addition. When will you merge this into master?

**Comment by Ifnot** [comment]
The contributors problem was not resolved, and i should look after a more clearer documentation if we add this feature. Or the usage will be less understandable

**Comment by markwylde** [comment]
Not sure why I put my own name in that authors field. I've removed it now as it's not necessary.

Can we merge this. I'd like to remove my fork.

**Comment by markwylde** [comment]
Removing my fork.

**Pull request closed without merging**
